version: "3.3"

services:
       wordpress:
              container_name: wordpress
              build: ./wordpress/ 
              restart: always
              networks:
                    - inception
              volumes:
                      - wp_data:/var/www/wordpress
              depends_on:
                  - mariadb
       mariadb:
              container_name: mariadb
              build: ./mariadb/
              networks:
                    - inception
              restart: always
              environment:
                 MYSQL_ROOT_PASSWORD: root
                 MYSQL_DATABASE: mariadb
                 MYSQL_USER: orbiay
                 MYSQL_PASSWORD: root
       nginx:
              container_name: nginx
              build: ./nginx/ 
              networks:
                    - inception
              restart: unless-stopped
              ports:
                      - "443:443"
              volumes:
                       - wp_data:/var/www/wordpress
              depends_on:
                  - wordpress
volumes:
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/orbiay/Desktop/Inception/wp-data


networks:
  inception:
    name: inception