version: "3.7"

services:
       wordpress:
              container_name: wordpress
              build: ./wordpress/ 
              #image: wordpress:php8.2-fpm-alpine
              restart: always
              networks:
                    - private_net
              ports:
                    - "9000:9000"
              volumes:
                      - wp_data:/var/www/wordpress
              depends_on:
                  - mariadb
       mariadb:
              container_name: mariadb
              #build: ./requirements/mariadb/ 
              image: mariadb
              networks:
                    - private_net
              restart: always
              ports:
                    - "3306:3306"
              environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: mariadb
                MYSQL_USER: root
                MYSQL_PASSWORD: root
       nginx:
              container_name: nginx
              build: ./nginx/ 
              #image: nginx
              networks:
                    - private_net
              restart: unless-stopped
              ports:
                      - "443:443"
              volumes:
                       - wp_data:/var/www/wordpress
              depends_on:
                  - wordpress

volumes:
        wp_data:

networks:
      private_net: